version: '3'

vars:
  CONTAINER_TOOL: podman # [ docker, podman ]
  VERSION_TAG:
    sh: git symbolic-ref -q --short HEAD 2>/dev/null || git describe --tags --exact-match 2>/dev/null || echo "$VLD_VERSION"

tasks:
  build:
    desc: Build the video-ligtning-detector for the current system (Windows or Linux) for the AMD64 architecture without debug symbols.
    vars:
      LDFLAG_VERSION: github.com/Krzysztofz01/video-lightning-detector/cmd.Version={{.VERSION_TAG}}
    cmds:
      - cmd: GOOS=windows GOARCH=amd64 go build -v -trimpath -ldflags="-s -w -X {{.LDFLAG_VERSION}}" -o bin/vld.exe .
        platforms: [ windows ]
      - cmd: GOOS=linux GOARCH=amd64 go build -v -trimpath -ldflags="-s -w -X {{.LDFLAG_VERSION}}" -o bin/vld .
        platforms: [ linux ]
      - cmd: cp LICENSE bin/LICENSE
      - cmd: cp NOTICES bin/NOTICES

  build:image:
    desc: Build the video-lightning-detector container image with the current version and latest tag.
    vars:
      SPECIFIC_TAG: vld:{{.VERSION_TAG}}
      LATEST_TAG: vld:latest
    cmds:
      - cmd: "{{.CONTAINER_TOOL}} build --tag {{.SPECIFIC_TAG}} --build-arg VERSION={{.VERSION_TAG}} ."
      - cmd: "{{.CONTAINER_TOOL}} tag {{.SPECIFIC_TAG}} {{.LATEST_TAG}}"

  test:
    desc: Run tests for all packages.
    cmds:
      - go test ./...

  test:cover:
    desc: Run tests for all packages and generate a coverage report.
    vars:
      COVERAGE: coverage.out
    cmds:
      - go test -coverprofile {{.COVERAGE}} ./...
      - go tool cover -html {{.COVERAGE}}

  check:
    desc: Print the version of the Golang compiler and installed Ffmpeg tools.
    cmds:
       - go version
       - ffmpeg -hide_banner -version | head -n 1
       - ffprobe -hide_banner -version | head -n 1
